---
name: Increment Version
on:
  push:
    paths:
      - build.gradle
    branches: main
  workflow_dispatch:

jobs:
  version-increment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: version-increment
    steps:
      - name: Check out OpenSearch repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run gradle task
        id: gradle
        run: |
          ./gradlew updateVersion

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          push-to-fork: opensearch-ci-bot/opensearch-build-libraries
          token: ${{ secrets.OPENSEARCH_CI_BOT_TOKEN }}
          base: '13.x'
          committer: opensearch-ci-bot <opensearch-infra@amazon.com>
          author: opensearch-ci-bot <opensearch-infra@amazon.com>
          commit-message: |
            Increment jenkins library version

            Signed-off-by: opensearch-ci-bot <opensearch-infra@amazon.com>
          delete-branch: true
          branch: create-pull-request
          title: '[AUTO] Increment jenkins library version'
          body: |
            - Increment jenkins library version.
      - name: Check outputs
        run: |-
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
